//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphanem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaynaklar
    {
        public int kaynay_id { get; set; }
        public string kaynak_ad { get; set; }
        public string kaynak_yazar { get; set; }
        public string kaynak_yayinevi { get; set; }
        public Nullable<int> kaynak_sayfasayisi { get; set; }
        public Nullable<System.DateTime> kaynak_basimtarihi { get; set; }
    }
}
